apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    kubernetes.io/metadata.name: platform
    pod-security.kubernetes.io/enforce: restricted
    gitops.jenkins-x.io/pipeline: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kubernetes.io/metadata.name: monitoring
