apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    spec:
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["python", "worker.py"]
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          {{- toYaml .valueFrom | nindent 10 }}
          {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
